name: pexels_api
version: 0.2.0
description: Unofficial wrapper of Pexels REST API for the Dart Language.
repository: https://github.com/purefundev/flutter_pexels_api
homepage: https://purefun.dev
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  http: ^0.13.5
dev_dependencies:
  test : ^1.17.3
